### ISSUE TITLE
add Getting Started instructions

### ISSUE THREAD

**Issue by connor11528** [cdoghoneypig/linkedin-analyzer#2]
Hey I would like to run the project on my local machine. I cloned the repo and then cd'd into it. Then ran `python linked-results-scraper1.py` but I got an error.

How do I run this program on my own machine?

Error:
```
$ python linked-results-scraper1.py 
  File "linked-results-scraper1.py", line 38
    print("saving",out_filename, end=', ')
                                    ^
SyntaxError: invalid syntax
```

**Comment by cdoghoneypig** [comment]
It's written in Python 3.5
Pretty sure that's the problem.
I'm happy to see you're interested in using it! I added to the readme file. It's a very bare bones tool, more just a place for me to store this project. Once I got the results I was looking for, I really stopped working on it

**Comment by connor11528** [comment]
Okay for sure! Python 3.5 got it. Thank you

**Comment by connor11528** [comment]
Hey so i upgraded to python 3.5 and made alias in .bash_profile as outlined [here](http://stackoverflow.com/questions/18425379/how-to-set-pythons-default-version-to-3-3-on-os-x).

Run analyze1.py and get a new error:

```
$ python analyze1.py                 
Traceback (most recent call last):
  File "analyze1.py", line 10, in <module>
    import xlwt
ImportError: No module named 'xlwt'
```

I ran `sudo pip install xlwt` prior to that but no dice. Do i install these modules globally or do I need to set up a virtual environment to run the program?

Feel like kind of a noob but also get an error with the other python file. Do I need to create these directories?

```
$ python linked-results-scraper1.py
Traceback (most recent call last):
  File "linked-results-scraper1.py", line 22, in <module>
    for html_file in os.listdir(localdir):
FileNotFoundError: [Errno 2] No such file or directory: 'html/'
```

Thank you. Any help much appreciated!

**Comment by cdoghoneypig** [comment]
xlwt - I installed it globally, but I don't think that should matter. I'm not sure why xlwt isn't working for you...

The html folders: 
What I have here is just the tool, not the data that I ran it on. The ugly bit is that, if I put that data here, I am posting the shortened profiles of hundreds of people here. I wouldn't mind sending it to you privately, if you're interested.
